version: '3.8'

services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      # Синхронизация папки, чтобы изменения кода работали без перезагрузки
      - .:/app
      # Исключаем папку node_modules контейнера из синхронизации
      - /app/node_modules
    env_file:
      # Явно указываем, откуда брать ключи
      - .env